import mysql.connector
from mysql.connector import Error

# 特徵清單（Edge-IIoTset 的 182 個特徵）
features_list = [
    {"column_name": "frame.cap_len", "chinese_name": "擷取的封包長度", "layer": "Frame", "category_type": "離散型"},
    {"column_name": "frame.encap_type", "chinese_name": "封包的封裝類型", "layer": "Frame", "category_type": "離散型"},
    {"column_name": "frame.ignored", "chinese_name": "封包是否被分析工具忽略", "layer": "Frame", "category_type": "離散型"},
    {"column_name": "frame.interface_id", "chinese_name": "捕獲封包的網絡介面識別碼", "layer": "Frame", "category_type": "字串型"},
    {"column_name": "frame.interface_name", "chinese_name": "捕獲封包的網絡介面名稱", "layer": "Frame", "category_type": "字串型"},
    {"column_name": "frame.len", "chinese_name": "封包的實際總長度", "layer": "Frame", "category_type": "離散型"},
    {"column_name": "frame.marked", "chinese_name": "封包是否被手動標記", "layer": "Frame", "category_type": "離散型"},
    {"column_name": "frame.number", "chinese_name": "封包的序號", "layer": "Frame", "category_type": "離散型"},
    {"column_name": "frame.offset_shift", "chinese_name": "時間偏移修正值", "layer": "Frame", "category_type": "連續型"},
    {"column_name": "frame.protocols", "chinese_name": "封包包含的所有協議層列表", "layer": "Frame", "category_type": "字串型"},
    {"column_name": "frame.section_number", "chinese_name": "封包所在的數據區段編號", "layer": "Frame", "category_type": "離散型"},
    {"column_name": "frame.time", "chinese_name": "封包捕獲的格式化時間", "layer": "Frame", "category_type": "字串型"},
    {"column_name": "frame.time_delta", "chinese_name": "與前一個封包的時間差", "layer": "Frame", "category_type": "連續型"},
    {"column_name": "frame.time_delta_displayed", "chinese_name": "與前一個顯示封包的時間差", "layer": "Frame", "category_type": "連續型"},
    {"column_name": "frame.time_epoch", "chinese_name": "封包捕獲的Unix時間戳", "layer": "Frame", "category_type": "連續型"},
    {"column_name": "frame.time_relative", "chinese_name": "相對於第一個封包的時間差", "layer": "Frame", "category_type": "連續型"},
    {"column_name": "frame.time_utc", "chinese_name": "封包捕獲的UTC格式時間戳", "layer": "Frame", "category_type": "字串型"},
    {"column_name": "eth.addr", "chinese_name": "以太網地址", "layer": "Ethernet", "category_type": "字串型"},
    {"column_name": "eth.addr.oui", "chinese_name": "以太網地址的組織唯一識別碼", "layer": "Ethernet", "category_type": "字串型"},
    {"column_name": "eth.addr.oui_resolved", "chinese_name": "OUI對應的製造商名稱", "layer": "Ethernet", "category_type": "字串型"},
    {"column_name": "eth.addr_resolved", "chinese_name": "解析後的MAC地址", "layer": "Ethernet", "category_type": "字串型"},
    {"column_name": "eth.dst", "chinese_name": "目的MAC地址", "layer": "Ethernet", "category_type": "字串型"},
    {"column_name": "eth.dst.ig", "chinese_name": "目的MAC地址是否為群組地址", "layer": "Ethernet", "category_type": "離散型"},
    {"column_name": "eth.dst.lg", "chinese_name": "目的MAC地址是否為本地管理地址", "layer": "Ethernet", "category_type": "離散型"},
    {"column_name": "eth.dst.oui", "chinese_name": "目的MAC地址的OUI部分", "layer": "Ethernet", "category_type": "字串型"},
    {"column_name": "eth.dst.oui_resolved", "chinese_name": "目的MAC地址的OUI對應製造商名稱", "layer": "Ethernet", "category_type": "字串型"},
    {"column_name": "eth.dst_resolved", "chinese_name": "解析後的目的MAC地址", "layer": "Ethernet", "category_type": "字串型"},
    {"column_name": "eth.ig", "chinese_name": "MAC地址是否為群播地址", "layer": "Ethernet", "category_type": "離散型"},
    {"column_name": "eth.lg", "chinese_name": "MAC地址是否為本地管理地址", "layer": "Ethernet", "category_type": "離散型"},
    {"column_name": "eth.src", "chinese_name": "來源MAC地址", "layer": "Ethernet", "category_type": "字串型"},
    {"column_name": "eth.src.ig", "chinese_name": "來源MAC地址是否為群組地址", "layer": "Ethernet", "category_type": "離散型"},
    {"column_name": "eth.src.lg", "chinese_name": "來源MAC地址是否為本地管理地址", "layer": "Ethernet", "category_type": "離散型"},
    {"column_name": "eth.src.oui", "chinese_name": "來源MAC地址的OUI部分", "layer": "Ethernet", "category_type": "字串型"},
    {"column_name": "eth.src.oui_resolved", "chinese_name": "來源MAC地址的OUI對應製造商名稱", "layer": "Ethernet", "category_type": "字串型"},
    {"column_name": "eth.src_resolved", "chinese_name": "解析後的來源MAC地址", "layer": "Ethernet", "category_type": "字串型"},
    {"column_name": "eth.type", "chinese_name": "以太網類型欄位", "layer": "Ethernet", "category_type": "字串型"},
    {"column_name": "arp.dst.proto_ipv4", "chinese_name": "目的協議地址（IPv4地址）", "layer": "ARP", "category_type": "字串型"},
    {"column_name": "arp.opcode", "chinese_name": "ARP操作代碼", "layer": "ARP", "category_type": "離散型"},
    {"column_name": "arp.hw.size", "chinese_name": "硬體地址長度", "layer": "ARP", "category_type": "離散型"},
    {"column_name": "arp.src.proto_ipv4", "chinese_name": "來源協議地址（IPv4地址）", "layer": "ARP", "category_type": "字串型"},
    {"column_name": "ip.addr", "chinese_name": "來源或目的IP地址", "layer": "IP", "category_type": "字串型"},
    {"column_name": "ip.checksum", "chinese_name": "IP標頭的檢查碼值", "layer": "IP", "category_type": "字串型"},
    {"column_name": "ip.checksum.status", "chinese_name": "IP檢查碼的驗證狀態", "layer": "IP", "category_type": "字串型"},
    {"column_name": "ip.dsfield", "chinese_name": "服務類型字段", "layer": "IP", "category_type": "離散型"},
    {"column_name": "ip.dsfield.dscp", "chinese_name": "差異化服務碼點", "layer": "IP", "category_type": "離散型"},
    {"column_name": "ip.dsfield.ecn", "chinese_name": "顯式擁塞通知碼點", "layer": "IP", "category_type": "離散型"},
    {"column_name": "ip.dst", "chinese_name": "目的IP地址", "layer": "IP", "category_type": "字串型"},
    {"column_name": "ip.dst_host", "chinese_name": "解析後的目的IP主機名稱", "layer": "IP", "category_type": "字串型"},
    {"column_name": "ip.flags", "chinese_name": "IP標誌欄位", "layer": "IP", "category_type": "字串型"},
    {"column_name": "ip.flags.df", "chinese_name": "不分段標誌", "layer": "IP", "category_type": "離散型"},
    {"column_name": "ip.flags.mf", "chinese_name": "更多分段標誌", "layer": "IP", "category_type": "離散型"},
    {"column_name": "ip.flags.rb", "chinese_name": "保留標誌", "layer": "IP", "category_type": "離散型"},
    {"column_name": "ip.frag_offset", "chinese_name": "分段偏移量", "layer": "IP", "category_type": "離散型"},
    {"column_name": "ip.hdr_len", "chinese_name": "IP標頭長度", "layer": "IP", "category_type": "離散型"},
    {"column_name": "ip.host", "chinese_name": "來源或目的主機名稱", "layer": "IP", "category_type": "字串型"},
    {"column_name": "ip.id", "chinese_name": "封包識別碼", "layer": "IP", "category_type": "離散型"},
    {"column_name": "ip.len", "chinese_name": "IP封包總長度", "layer": "IP", "category_type": "離散型"},
    {"column_name": "ip.proto", "chinese_name": "上層協議編號", "layer": "IP", "category_type": "離散型"},
    {"column_name": "ip.src", "chinese_name": "來源IP地址", "layer": "IP", "category_type": "字串型"},
    {"column_name": "ip.src_host", "chinese_name": "解析後的來源IP主機名稱", "layer": "IP", "category_type": "字串型"},
    {"column_name": "ip.ttl", "chinese_name": "存活時間（TTL）", "layer": "IP", "category_type": "離散型"},
    {"column_name": "ip.version", "chinese_name": "IP協議版本", "layer": "IP", "category_type": "離散型"},
    {"column_name": "icmp.checksum", "chinese_name": "ICMP封包的檢查碼值", "layer": "ICMP", "category_type": "字串型"},
    {"column_name": "icmp.seq_le", "chinese_name": "序列號（小端格式）", "layer": "ICMP", "category_type": "離散型"},
    {"column_name": "icmp.transmit_timestamp", "chinese_name": "傳送時間戳", "layer": "ICMP", "category_type": "連續型"},
    {"column_name": "icmp.unused", "chinese_name": "未使用欄位", "layer": "ICMP", "category_type": "離散型"},
    {"column_name": "tcp.ack", "chinese_name": "確認號", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.ack_raw", "chinese_name": "確認號的原始格式", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.analysis.ack_rtt", "chinese_name": "往返時間（RTT）", "layer": "TCP", "category_type": "連續型"},
    {"column_name": "tcp.analysis.acks_frame", "chinese_name": "被確認的封包的框架編號", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.analysis.bytes_in_flight", "chinese_name": "已發送但尚未被確認的字節數", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.analysis.initial_rtt", "chinese_name": "初始往返時間估計", "layer": "TCP", "category_type": "連續型"},
    {"column_name": "tcp.analysis.push_bytes_sent", "chinese_name": "帶有PUSH標誌發送的字節數", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.analysis.reused_ports", "chinese_name": "是否重複使用了端口", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.checksum", "chinese_name": "TCP標頭和負載的檢查碼", "layer": "TCP", "category_type": "字串型"},
    {"column_name": "tcp.checksum.status", "chinese_name": "檢查碼驗證狀態", "layer": "TCP", "category_type": "字串型"},
    {"column_name": "tcp.completeness.ack", "chinese_name": "封包是否包含ACK標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.completeness.data", "chinese_name": "封包是否包含數據負載", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.completeness.fin", "chinese_name": "封包是否包含FIN標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.completeness.rst", "chinese_name": "封包是否包含RST標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.completeness.str", "chinese_name": "封包完整性的文字描述", "layer": "TCP", "category_type": "字串型"},
    {"column_name": "tcp.completeness.syn", "chinese_name": "封包是否包含SYN標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.completeness.syn-ack", "chinese_name": "封包是否包含SYN/ACK標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.connection.fin", "chinese_name": "連線是否通過FIN正常關閉", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.connection.fin_active", "chinese_name": "是否主動發起FIN關閉連線", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.connection.fin_passive", "chinese_name": "是否被動接受FIN關閉連線", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.connection.rst", "chinese_name": "連線是否被RST重置", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.connection.syn", "chinese_name": "連線是否包含SYN標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.connection.synack", "chinese_name": "連線是否包含SYN-ACK標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.dstport", "chinese_name": "目的端口號", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.flags", "chinese_name": "TCP標誌位元組", "layer": "TCP", "category_type": "字串型"},
    {"column_name": "tcp.flags.ack", "chinese_name": "ACK標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.flags.ae", "chinese_name": "附加擴展標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.flags.cwr", "chinese_name": "擁塞窗口縮減標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.flags.ece", "chinese_name": "擁塞通知回應標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.flags.fin", "chinese_name": "FIN標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.flags.push", "chinese_name": "PUSH標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.flags.res", "chinese_name": "保留標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.flags.reset", "chinese_name": "RST標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.flags.str", "chinese_name": "TCP標誌的字串表示", "layer": "TCP", "category_type": "字串型"},
    {"column_name": "tcp.flags.syn", "chinese_name": "SYN標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.flags.urg", "chinese_name": "URG標誌", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.hdr_len", "chinese_name": "TCP標頭長度", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.len", "chinese_name": "TCP有效負載長度", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.nxtseq", "chinese_name": "下一個預期的序號", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.option_kind", "chinese_name": "TCP選項種類代碼", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.option_len", "chinese_name": "TCP選項長度", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.options", "chinese_name": "TCP選項集合", "layer": "TCP", "category_type": "字串型"},
    {"column_name": "tcp.options.mss", "chinese_name": "最大段大小（MSS）", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.options.mss_val", "chinese_name": "MSS的具體數值", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.options.sack_perm", "chinese_name": "是否允許選擇性確認（SACK）", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.options.timestamp", "chinese_name": "時間戳選項", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.options.timestamp.tsecr", "chinese_name": "時間戳回應值", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.options.timestamp.tsval", "chinese_name": "時間戳值", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.options.wscale", "chinese_name": "窗口縮放選項", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.options.wscale.multiplier", "chinese_name": "窗口縮放乘數", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.options.wscale.shift", "chinese_name": "窗口縮放偏移量", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.payload", "chinese_name": "TCP負載數據", "layer": "TCP", "category_type": "字串型"},
    {"column_name": "tcp.pdu.size", "chinese_name": "協議數據單元（PDU）區塊大小", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.port", "chinese_name": "TCP通用端口號", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.seq", "chinese_name": "序號", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.seq_raw", "chinese_name": "原始序號", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.srcport", "chinese_name": "來源端口號", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.stream", "chinese_name": "TCP流的唯一識別編號", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.time_delta", "chinese_name": "與前一個TCP封包的時間差", "layer": "TCP", "category_type": "連續型"},
    {"column_name": "tcp.time_relative", "chinese_name": "相對於流開始的時間", "layer": "TCP", "category_type": "連續型"},
    {"column_name": "tcp.urgent_pointer", "chinese_name": "緊急數據指標", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.window_size", "chinese_name": "接收窗口大小", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.window_size_scalefactor", "chinese_name": "窗口縮放因子", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "tcp.window_size_value", "chinese_name": "縮放後的實際窗口大小", "layer": "TCP", "category_type": "離散型"},
    {"column_name": "udp.port", "chinese_name": "UDP端口號", "layer": "UDP", "category_type": "離散型"},
    {"column_name": "udp.stream", "chinese_name": "UDP流的唯一識別編號", "layer": "UDP", "category_type": "離散型"},
    {"column_name": "udp.time_delta", "chinese_name": "與前一個UDP封包的時間差", "layer": "UDP", "category_type": "連續型"},
    {"column_name": "dns.qry.name", "chinese_name": "DNS查詢的域名", "layer": "DNS", "category_type": "字串型"},
    {"column_name": "dns.qry.name.len", "chinese_name": "查詢域名的長度", "layer": "DNS", "category_type": "離散型"},
    {"column_name": "dns.qry.qu", "chinese_name": "DNS查詢類型代碼", "layer": "DNS", "category_type": "離散型"},
    {"column_name": "dns.qry.type", "chinese_name": "DNS查詢記錄類型", "layer": "DNS", "category_type": "離散型"},
    {"column_name": "dns.retransmission", "chinese_name": "封包是否為重新傳送的DNS封包", "layer": "DNS", "category_type": "離散型"},
    {"column_name": "dns.retransmit_request", "chinese_name": "封包是否為重新傳送的DNS請求", "layer": "DNS", "category_type": "離散型"},
    {"column_name": "dns.retransmit_request_in", "chinese_name": "對應原始DNS請求的框架編號", "layer": "DNS", "category_type": "離散型"},
    {"column_name": "http.file_data", "chinese_name": "HTTP傳輸的檔案數據內容", "layer": "HTTP", "category_type": "字串型"},
    {"column_name": "http.content_length", "chinese_name": "HTTP內容長度", "layer": "HTTP", "category_type": "離散型"},
    {"column_name": "http.request.uri.query", "chinese_name": "HTTP請求的查詢參數", "layer": "HTTP", "category_type": "字串型"},
    {"column_name": "http.request.method", "chinese_name": "HTTP請求方法", "layer": "HTTP", "category_type": "字串型"},
    {"column_name": "http.referer", "chinese_name": "請求來源頁面URL", "layer": "HTTP", "category_type": "字串型"},
    {"column_name": "http.request.full_uri", "chinese_name": "完整的HTTP請求URI", "layer": "HTTP", "category_type": "字串型"},
    {"column_name": "http.request.version", "chinese_name": "HTTP協議版本", "layer": "HTTP", "category_type": "字串型"},
    {"column_name": "http.response", "chinese_name": "封包是否為HTTP回應", "layer": "HTTP", "category_type": "離散型"},
    {"column_name": "http.tls_port", "chinese_name": "與TLS加密相關的端口號", "layer": "TLS", "category_type": "離散型"},
    {"column_name": "mqtt.clientid", "chinese_name": "MQTT客戶端唯一識別碼", "layer": "MQTT", "category_type": "字串型"},
    {"column_name": "mqtt.clientid_len", "chinese_name": "客戶端識別碼的長度", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.conack.flags", "chinese_name": "MQTT連線確認的標誌位元組", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.conack.flags.reserved", "chinese_name": "連線確認中的保留標誌", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.conack.flags.sp", "chinese_name": "會話存在標誌", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.conack.val", "chinese_name": "MQTT v3連線確認代碼", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.conflag.cleansess", "chinese_name": "是否清除之前的會話狀態", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.conflag.passwd", "chinese_name": "連線是否包含密碼欄位", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.conflag.qos", "chinese_name": "遺囑訊息的服務品質等級", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.conflag.reserved", "chinese_name": "連線標誌中的保留欄位", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.conflag.retain", "chinese_name": "遺囑訊息是否需要保留", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.conflags", "chinese_name": "整合的連線標誌位元組", "layer": "MQTT", "category_type": "字串型"},
    {"column_name": "mqtt.conflag.uname", "chinese_name": "連線是否包含使用者名稱欄位", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.conflag.willflag", "chinese_name": "是否啟用遺囑訊息", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.connack.reason_code", "chinese_name": "MQTT v5連線確認原因碼", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.dupflag", "chinese_name": "訊息是否為重複發送的封包", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.hdrflags", "chinese_name": "MQTT固定標頭的標誌位元組", "layer": "MQTT", "category_type": "字串型"},
    {"column_name": "mqtt.hdr_reserved", "chinese_name": "固定標頭中的保留標誌", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.kalive", "chinese_name": "保持連線時間", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.len", "chinese_name": "訊息剩餘長度欄位", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.msg", "chinese_name": "MQTT訊息的主體內容", "layer": "MQTT", "category_type": "字串型"},
    {"column_name": "mqtt.msgid", "chinese_name": "訊息的唯一識別碼", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.msgtype", "chinese_name": "訊息類型", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.passwd", "chinese_name": "MQTT連線的密碼", "layer": "MQTT", "category_type": "字串型"},
    {"column_name": "mqtt.passwd_len", "chinese_name": "密碼欄位的長度", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.properties", "chinese_name": "MQTT v5的屬性清單", "layer": "MQTT", "category_type": "字串型"},
    {"column_name": "mqtt.property_id", "chinese_name": "屬性代碼識別碼", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.property_len", "chinese_name": "屬性欄位的長度", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.prop_number", "chinese_name": "屬性中的數值", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.prop_string", "chinese_name": "屬性中的字串值", "layer": "MQTT", "category_type": "字串型"},
    {"column_name": "mqtt.prop_string_len", "chinese_name": "屬性字串的長度", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.proto_len", "chinese_name": "協議名稱的長度", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.protoname", "chinese_name": "協議名稱", "layer": "MQTT", "category_type": "字串型"},
    {"column_name": "mqtt.qos", "chinese_name": "服務品質等級", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.retain", "chinese_name": "訊息是否要求Broker保留", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.suback.reason_code", "chinese_name": "訂閱回應的原因碼", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.sub.qos", "chinese_name": "訂閱的QoS等級", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.subscription_options", "chinese_name": "訂閱選項的位元組", "layer": "MQTT", "category_type": "字串型"},
    {"column_name": "mqtt.subscription_options_nl", "chinese_name": "是否不保留訊息", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.subscription_options_qos", "chinese_name": "訂閱的QoS等級", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.subscription_options_rap", "chinese_name": "是否僅接收最新的保留訊息", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.subscription_options_reserved", "chinese_name": "訂閱選項中的保留位元", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.subscription_options_retain", "chinese_name": "是否傳送保留訊息", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.topic", "chinese_name": "訂閱或發佈的主題名稱", "layer": "MQTT", "category_type": "字串型"},
    {"column_name": "mqtt.topic_len", "chinese_name": "主題名稱的長度", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.unknown_version", "chinese_name": "未知的MQTT協議版本標記", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.username", "chinese_name": "MQTT連線的使用者名稱", "layer": "MQTT", "category_type": "字串型"},
    {"column_name": "mqtt.username_len", "chinese_name": "使用者名稱的長度", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.ver", "chinese_name": "MQTT協議版本", "layer": "MQTT", "category_type": "離散型"},
    {"column_name": "mqtt.msg_decoded_as", "chinese_name": "訊息解碼的協議類型", "layer": "MQTT", "category_type": "字串型"},
    {"column_name": "mbtcp.len", "chinese_name": "Modbus TCP數據長度", "layer": "Modbus TCP", "category_type": "離散型"},
    {"column_name": "mbtcp.trans_id", "chinese_name": "Modbus交易識別碼", "layer": "Modbus TCP", "category_type": "離散型"},
    {"column_name": "mbtcp.unit_id", "chinese_name": "Modbus單元識別碼", "layer": "Modbus TCP", "category_type": "離散型"},
    {"column_name": "data.data", "chinese_name": "封包的原始有效負載數據", "layer": "其他", "category_type": "字串型"},
    {"column_name": "data.len", "chinese_name": "有效負載數據的長度", "layer": "其他", "category_type": "離散型"}
]

try:
    # 連接到 MySQL
    conn = mysql.connector.connect(
        host="localhost",
        user="root",
        password="",  # 若有密碼，請填入
        database="feature_db"
    )
    cursor = conn.cursor()

    # 清空現有數據（可選，若需保留現有數據則註釋掉）
    cursor.execute("DELETE FROM features")

    # 插入特徵
    for feature in features_list:
        cursor.execute(
            """
            INSERT INTO features (column_name, chinese_name, layer, category_type)
            VALUES (%s, %s, %s, %s)
            """,
            (feature["column_name"], feature["chinese_name"], feature["layer"], feature["category_type"])
        )

    # 提交並關閉
    conn.commit()
    print("成功匯入 {} 個特徵到 features 表格！".format(len(features_list)))

except Error as e:
    print(f"MySQL 錯誤: {e}")

finally:
    if cursor:
        cursor.close()
    if conn:
        conn.close()